#!/bin/sh
# Build a static libffi.a for HarmonyOS (aarch64-linux-ohos, musl) from an
# upstream libffi source tree.
#
# Why a hand-written build instead of autotools: libffi's `configure` cannot run
# in this sandbox (config.guess needs HOME, config.status' temp dir is denied,
# `make -j` needs a jobserver FIFO). The TU set is small and stable, so we
# compile it directly — same spirit as the libffi path in build_lwjgl_natives.sh.
#
# Why it is needed at all: LWJGL >= 3.4.x links libffi into liblwjgl.so and, from
# libffi 3.8.0, calls the new `ffi_call_plan_*` / `ffi_get_*` entry points, so the
# old 3.4.4 static lib is not link-compatible. LWJGL ships libffi *headers only*.
#
# Standalone: every path is passed in; nothing is derived from the caller layout.
#
# Usage:
#   sh build_libffi.sh --src DIR --sdk-native DIR --out DIR [--build DIR]
#                      [--api N] [--arch NAME] [--version V] [--version-number N]
#
# Required:
#   --src DIR         libffi source tree (has include/ffi.h.in + src/aarch64)
#   --sdk-native DIR  OHOS SDK native dir (sysroot + llvm toolchain)
#   --out DIR         output dir; receives libffi.a
# Optional:
#   --build DIR       scratch dir (default <out>/build)
#   --api N           OHOS platform level (informational; default 23)
#   --arch NAME       OHOS arch (default arm64-v8a; only arm64-v8a here)
#   --version V       libffi version string for ffi.h (default: from ffi.h.in @@)
#   --version-number N numeric version (default: from ffi.h.in @@)
#   -h, --help        show this help
#
# Produces a stripped-shape static archive and asserts the modern entry points.
set -e

HERE="$(cd "$(dirname "$0")" && pwd)"

usage() { sed -n '2,36p' "$0" | sed 's/^# \{0,1\}//'; }

SRC=""; SDK_NATIVE=""; OUT=""; BUILD=""; API=23; ARCH=arm64-v8a; VER=""; VERN=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    --src)            SRC="$2";        shift 2 ;;
    --sdk-native)     SDK_NATIVE="$2"; shift 2 ;;
    --out)            OUT="$2";        shift 2 ;;
    --build)          BUILD="$2";      shift 2 ;;
    --api)            API="$2";        shift 2 ;;
    --arch)           ARCH="$2";       shift 2 ;;
    --version)        VER="$2";        shift 2 ;;
    --version-number) VERN="$2";       shift 2 ;;
    -h|--help)        usage; exit 0 ;;
    *) echo "unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done
[ -n "$SRC" ]        || { echo "error: --src is required" >&2; exit 2; }
[ -n "$SDK_NATIVE" ] || { echo "error: --sdk-native is required" >&2; exit 2; }
[ -n "$OUT" ]        || { echo "error: --out is required" >&2; exit 2; }

case "$ARCH" in
  arm64-v8a) TRIPLE="aarch64-linux-ohos"; TGT="AARCH64" ;;
  *) echo "error: unsupported --arch '$ARCH' (only arm64-v8a supported)" >&2; exit 2 ;;
esac

SRC="$(cd "$SRC" && pwd)"
mkdir -p "$OUT"; OUT="$(cd "$OUT" && pwd)"
[ -n "$BUILD" ] || BUILD="$OUT/build"
mkdir -p "$BUILD/obj"
BUILD="$(cd "$BUILD" && pwd)"

[ -f "$SRC/include/ffi.h.in" ] || { echo "error: not a libffi tree: $SRC" >&2; exit 2; }
[ -d "$SRC/src/aarch64" ]      || { echo "error: no src/aarch64 in $SRC" >&2; exit 2; }
[ -d "$SDK_NATIVE/sysroot" ]   || { echo "error: SDK sysroot not found: $SDK_NATIVE" >&2; exit 2; }

if [ -x "$SDK_NATIVE/llvm/bin/${TRIPLE}-clang" ]; then
  CC="$SDK_NATIVE/llvm/bin/${TRIPLE}-clang"
else
  CC="$SDK_NATIVE/llvm/bin/clang"
  TARGET_FLAGS="--target=$TRIPLE --sysroot=$SDK_NATIVE/sysroot"
fi
AR="$SDK_NATIVE/llvm/bin/llvm-ar"
NM="$SDK_NATIVE/llvm/bin/llvm-nm"

# ---- 1. ffi.h from ffi.h.in ------------------------------------------------
VERSION_STR="${VER:-3.8.0}"
[ -n "$VER" ] || VERSION_STR="$(sed -n 's/^AC_INIT(\[libffi\], \[\([0-9.]*\)\].*/\1/p' "$SRC/configure.ac" 2>/dev/null | head -1)"
[ -n "$VERSION_STR" ] || VERSION_STR="3.8.0"
if [ -z "$VERN" ]; then
  VERN="$(printf '%s' "$VERSION_STR" | awk -F. '{printf "%d%02d%02d", $1, $2, $3}')"
fi
sed -e "s/@VERSION@/$VERSION_STR/g" \
    -e "s/@TARGET@/$TGT/g" \
    -e "s/@HAVE_LONG_DOUBLE@/1/g" \
    -e "s/@FFI_EXEC_TRAMPOLINE_TABLE@/0/g" \
    -e "s/@FFI_VERSION_STRING@/$VERSION_STR/g" \
    -e "s/@FFI_VERSION_NUMBER@/$VERN/g" \
    "$SRC/include/ffi.h.in" > "$SRC/include/ffi.h"
left=$(grep -c '@[A-Z_]*@' "$SRC/include/ffi.h" || true)
[ "$left" -eq 0 ] || { echo "error: $left unresolved @placeholder@ in ffi.h" >&2; exit 1; }
echo "ffi.h: version=$VERSION_STR ($VERN)"

# ---- 2. fficonfig.h (hand-written; musl target) ----------------------------
cat > "$SRC/include/fficonfig.h" <<'FFICONFIG'
/* Generated by tools/lwjgl/build_libffi.sh for aarch64-linux-ohos (musl). */
#define STDC_HEADERS 1
#define HAVE_ALLOCA 1
#define HAVE_ALLOCA_H 1
#define HAVE_MEMCPY 1
#define HAVE_MEMMOVE 1
#define HAVE_MEMSET 1
#define HAVE_MMAP 1
#define HAVE_MMAP_ANON 1
#define HAVE_MMAP_FILE 1
#define HAVE_GETPAGESIZE 1
#define HAVE_MKOSTEMP 1
#define HAVE_MEMFD_CREATE 1
#define HAVE_MNTENT 1
#define HAVE_SYS_MMAN_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define HAVE_STRING_H 1
#define HAVE_STDLIB_H 1
#define HAVE_DLFCN_H 1
#define HAVE_HIDDEN_VISIBILITY_ATTRIBUTE 1
#define HAVE_LONG_DOUBLE 1
#define FFI_EXEC_STATIC_TRAMP 1
#define FFI_EXEC_TRAMPOLINE_TABLE 0
#define FFI_TMPDIR "/tmp"
#ifdef LIBFFI_ASM
#define FFI_HIDDEN(name) .hidden name
#else
#define FFI_HIDDEN __attribute__ ((visibility ("hidden")))
#endif
FFICONFIG

# ---- 3. compile TUs --------------------------------------------------------
CF="$TARGET_FLAGS -D__MUSL__ -O2 -fPIC -std=gnu11 \
-I$SRC/include -I$SRC/src -I$SRC/src/aarch64"
cd "$SRC"
for f in prep_cif types raw_api java_raw_api closures tramp; do
  "$CC" $CF -c "src/$f.c" -o "$BUILD/obj/$f.o"
done
"$CC" $CF -DHAVE_LONG_DOUBLE_VARIANT=0 -c src/aarch64/ffi.c -o "$BUILD/obj/ffi.o"
"$CC" $CF -c src/aarch64/sysv.S -o "$BUILD/obj/sysv.o"

"$AR" rcs "$OUT/libffi.a" "$BUILD/obj/"*.o

# ---- 4. assert the entry points LWJGL >= 3.4.x needs -----------------------
missing=""
for s in ffi_prep_cif ffi_call ffi_prep_closure_loc \
         ffi_get_version ffi_get_version_number ffi_get_default_abi \
         ffi_get_closure_size ffi_call_plan_alloc ffi_call_plan_invoke \
         ffi_call_plan_free ffi_call_plan_size; do
  "$NM" -g "$OUT/libffi.a" 2>/dev/null | grep -qE " T $s$" || missing="$missing $s"
done
[ -z "$missing" ] || { echo "error: libffi.a missing entry points:$missing" >&2; exit 1; }
echo "OK -> $OUT/libffi.a ($(wc -c < "$OUT/libffi.a") bytes, $(echo $s | wc -w) checks passed)"
